### ISSUE TITLE
Converting all stdout to stderr

### ISSUE THREAD

**Issue by noamteyssier** [FGRibreau/spinners#33]
Love the package - but didn't want the spinner outputs to get written to stdout when piping results outside of the program. 

Simple as replacing all `print!` and `println!` to `eprint!` and `eprintln!`

**Comment by ad4mx** [comment]
I think there should be an optional way to choose what stream to use instead of forcing printing to stderr. I'm not really sure how you would give the option to the user, but presenting the choices could look something like this:
```rust
#[derive(Default)]
pub enum Stream {
    #[default]
    Stdout,
    Stderr,
    Custom(Box<dyn Write>),
}
```
It would also require using `write!` and `writeln!` instead of `println!` and `print!`

**Comment by noamteyssier** [comment]
I added a similar enum `Stream` which handles the output. I think it could be modified to include a custom writer - but I had trouble passing a `dyn Write` through the move closure and also stay within the struct. I figured most people will only want to do stdout/stderr anyways so I didn't spend too much time trying to resolve it.

**Comment by ad4mx** [comment]
Yeah that makes sense.
